-- 1. Create databases for raw and analytics
CREATE OR REPLACE DATABASE CITYCART_RAW;
CREATE OR REPLACE DATABASE CITYCART_ANALYTICS;

-- 2. Create schemas in the raw database
CREATE OR REPLACE SCHEMA CITYCART_RAW.RAW_APP;
CREATE OR REPLACE SCHEMA CITYCART_RAW.RAW_OPS;
CREATE OR REPLACE SCHEMA CITYCART_RAW.RAW_MKT;
CREATE OR REPLACE SCHEMA CITYCART_RAW.RAW_SUPPORT;

-- 3. Create schemas in the analytics database
CREATE OR REPLACE SCHEMA CITYCART_ANALYTICS.DEV;
CREATE OR REPLACE SCHEMA CITYCART_ANALYTICS.PROD;
CREATE OR REPLACE SCHEMA CITYCART_ANALYTICS.QUALITY; -- for test failures later
