-- 1. Create a role for transformations
CREATE OR REPLACE ROLE CITYCART_TRANSFORM;

-- 2. Grant db-level privileges
GRANT USAGE ON WAREHOUSE CITYCART_WH TO ROLE CITYCART_TRANSFORM;

GRANT USAGE ON DATABASE CITYCART_RAW TO ROLE CITYCART_TRANSFORM;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CITYCART_RAW TO ROLE CITYCART_TRANSFORM;
GRANT SELECT ON ALL TABLES IN DATABASE CITYCART_RAW TO ROLE CITYCART_TRANSFORM;

GRANT USAGE, CREATE SCHEMA ON DATABASE CITYCART_ANALYTICS TO ROLE CITYCART_TRANSFORM;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CITYCART_ANALYTICS TO ROLE CITYCART_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE TEMPORARY TABLE
    ON ALL SCHEMAS IN DATABASE CITYCART_ANALYTICS
    TO ROLE CITYCART_TRANSFORM;

-- 3. Make sure role will see future objects too
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE CITYCART_RAW TO ROLE CITYCART_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN DATABASE CITYCART_RAW TO ROLE CITYCART_TRANSFORM;

GRANT USAGE ON FUTURE SCHEMAS IN DATABASE CITYCART_ANALYTICS TO ROLE CITYCART_TRANSFORM;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE TEMPORARY TABLE
    ON FUTURE SCHEMAS IN DATABASE CITYCART_ANALYTICS
    TO ROLE CITYCART_TRANSFORM;

-- 4. Create user for dbt
CREATE OR REPLACE USER DBT_CITYCART_USER
  LOGIN_NAME = 'dbt_citycart'
  TYPE = SERVICE
  RSA_PUBLIC_KEY = '-----BEGIN PUBLIC KEY-----
  ...
  -----END PUBLIC KEY-----'
  DEFAULT_ROLE = CITYCART_TRANSFORM
  DEFAULT_WAREHOUSE = CITYCART_WH
  DEFAULT_NAMESPACE = CITYCART_ANALYTICS.DEV
  COMMENT='DBT user used for data transformation';


-- 5. Grant role to user
GRANT ROLE CITYCART_TRANSFORM TO USER DBT_CITYCART_USER;

-- 6. Allow your admin role to manage this role
GRANT ROLE CITYCART_TRANSFORM TO ROLE SYSADMIN;
